spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
eureka:
  instance:
    preferIpAddress: true
    ip-address: 88.88.88.96

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
