spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
eureka:
  instance:
    preferIpAddress: true
    ip-address: ${ip}

ctrip:
  appid: 100003171
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
